# Generated by Django 4.0.3 on 2024-01-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_producto_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='producto',
            name='talla',
            field=models.TextField(default='M', max_length=1000),
            preserve_default=False,
        ),
    ]
