# Generated by Django 4.0.3 on 2024-01-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_rename_descripcion_producto_nombre_producto_talla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='cantidad',
            new_name='cantidad_talla_1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='talla',
            new_name='talla1',
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_talla_2',
            field=models.CharField(default=22, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='cantidad_talla_3',
            field=models.CharField(default='L', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='talla2',
            field=models.TextField(default='s', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='talla3',
            field=models.TextField(default='U', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
