# Generated by Django 4.0.3 on 2024-01-18 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_rename_cantidad_producto_cantidad_talla_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='talla1',
            new_name='stock_talla1',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='talla2',
            new_name='stock_talla2',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='talla3',
            new_name='stock_talla3',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_talla_1',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_talla_2',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_talla_3',
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_talla4',
            field=models.TextField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
