# Generated by Django 4.0.3 on 2024-01-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_rename_talla1_producto_stock_talla1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='stock_talla1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_talla2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_talla3',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_talla4',
            field=models.IntegerField(default=0),
        ),
    ]
