# Generated by Django 4.0.3 on 2024-01-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_rename_ventas_registro_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_ventas',
            name='total',
            field=models.CharField(default=20000, max_length=200),
            preserve_default=False,
        ),
    ]
