# Generated by Django 4.0.3 on 2024-01-27 12:07

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0011_userprofile_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
