# Generated by Django 4.0.3 on 2024-03-11 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0012_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('U', 'Usuario'), ('A', 'Administrador')], default='U', max_length=1),
        ),
    ]
